stages:
  parse:
    cmd: python3 src/parse_settlements.py
    deps:
      - data/GRID3_Nigeria_-_State_Boundaries.geojson
      - data/GRID3_Nigeria_Settlement_Extents_Version_01.02..geojson
      - src/parse_settlements.py
    params:
      - state
    outs:
      - data/parsed/${state}_population_locations.csv
  plot:
    cmd: python3 src/plot_locations.py
    deps:
      - data/parsed/${state}_population_locations.csv
      - src/plot_locations.py
    params:
      - state
    plots:
      - figs/${state}_population_locations.png
  configure:
    cmd: python3 src/configure_network.py
    deps:
      - data/parsed/${state}_population_locations.csv
      - src/configure_network.py
    params:
      - state
      - configure.knn
    outs:
      - data/configured/${state}_knn_graph.json